# Generated by Django 3.2.4 on 2021-06-21 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210622_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow_db',
            name='following',
        ),
        migrations.AddField(
            model_name='follow_db',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
