# Generated by Django 3.2.4 on 2021-06-29 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210629_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='skills',
            new_name='entity_type',
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=2560)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificates', models.CharField(max_length=2560)),
                ('profile_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
